export * from "./base_response"
export * as NewsResponse from "./news"
export * as LeadsResponse from "./leads"
export * as LoginResponse from "./login"
export * as TimetableTimeResponse from "./timetable_time"
export * as TimetableResponse from "./timetable"
export * as UserActivitySummaryResponse from "./user_activity_summary"
export * as UserResponse from "./user"
export * as ClassbookEntryResponse from "./classbook_entry"
export * as SurveyResponse from "./survey"
export * as SurveyVoteRequest from "./survey_post"
