# Format, Lint, Test and Build on Pull Request

name: Format, Lint, Test and Build on Pull Request

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    format-lint:
        name: Formats the project
        runs-on: ubuntu-latest
        steps:
            - name: Setup Repo
              uses: actions/checkout@v4

            - name: Enable Corepack before setting up Node
              run: corepack enable

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install

            - name: Format
              run: yarn worksapces:format:check

            - name: Lint
              run: yarn worksapces:lint:check
